### ISSUE TITLE
Add plotter support for i2c-based Sensirion SCD-30 NDIR carbon dioxide sensor

### ISSUE THREAD

**Issue by kevinjwalters** [pimoroni/EnviroPlus-FeatherWing#25]
Adafruit have a board for the Sensirion SCD-30 NDIR carbon dioxide (CO2) sensor and a library for it using i2c. This can connect to a few feathers via STEMMA QT and rest can be connected to the `SDA`/`SCL` pins. This would make a nice addition to the Enviro+ FeatherWing.

**Comment by Gadgetoid** [comment]
Merged! Thank you!
