### ISSUE TITLE
Make example name compatible with import

### ISSUE THREAD

**Issue by dglaude** [pimoroni/EnviroPlus-FeatherWing#6]
I had trouble to test the example using import.
Avoiding the caracter "-" and "&" and replacing this by "_" would help.

import bme280_simple

**Comment by Gadgetoid** [comment]
Is there a specific reason why you might import examples in this way?

**Comment by dglaude** [comment]
Well, how else do you run them?
Rename them to main.py?

Typically I would run them from the REPL, or have a main.py that import the example I want to run.

Any other reason why in the "low-mem" example you provide as *.MPY files do not use "-"?

**Comment by Gadgetoid** [comment]
Beats me - https://github.com/pimoroni/EnviroPlus-FeatherWing/graphs/contributors 😆

I had as little to do with writing this library as I could possibly muster and my experience with MicroPython extends to the BBC micro:bit where the concept of importing anything longer than a few lines is entirely alien and blows the memory limit. These questions are sincere.

I'm guessing you can preload all of the examples onto the device and run the ones you want using `import`?

**Comment by tannewt** [comment]
@Gadgetoid A few folks use import to run a particular example without having to rename it to the generic `code.py`

**Comment by Gadgetoid** [comment]
That makes sense. Thanks!

As I eluded- trying to do that on micro:bit would be bad times, which is why I always preferred PXT/MakeCode.

**Comment by dglaude** [comment]
Let's close this.
